# Generated by Django 4.2.23 on 2025-08-07 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва системи')),
                ('system_type', models.CharField(choices=[('web', 'Веб-система'), ('database', 'База даних'), ('server', 'Сервер'), ('network', 'Мережеве обладнання'), ('cloud', 'Хмарний сервіс'), ('software', 'Програмне забезпечення'), ('service', 'Сервіс'), ('other', 'Інше')], default='web', max_length=20, verbose_name='Тип системи')),
                ('url', models.URLField(blank=True, verbose_name='URL/Адреса')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адреса')),
                ('port', models.PositiveIntegerField(blank=True, null=True, verbose_name='Порт')),
                ('description', models.TextField(blank=True, verbose_name='Опис системи')),
                ('criticality', models.CharField(choices=[('low', 'Низька'), ('medium', 'Середня'), ('high', 'Висока'), ('critical', 'Критична')], default='medium', max_length=10, verbose_name='Критичність')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('administrators', models.ManyToManyField(blank=True, related_name='administered_systems', to=settings.AUTH_USER_MODEL, verbose_name='Адміністратори')),
            ],
            options={
                'verbose_name': 'Система',
                'verbose_name_plural': 'Системи',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва категорії')),
                ('description', models.TextField(blank=True, verbose_name='Опис категорії')),
                ('icon', models.CharField(blank=True, help_text='CSS клас або назва іконки', max_length=50, verbose_name='Іконка')),
                ('color', models.CharField(default='#6366f1', help_text='Hex код кольору (#ffffff)', max_length=7, verbose_name='Колір')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Категорія систем',
                'verbose_name_plural': 'Категорії систем',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name="Ім'я користувача")),
                ('_encrypted_password', models.TextField(blank=True, verbose_name='Зашифрований пароль')),
                ('account_type', models.CharField(choices=[('admin', 'Адміністратор'), ('user', 'Користувач'), ('service', 'Сервісний'), ('readonly', 'Тільки читання'), ('api', 'API ключ'), ('other', 'Інше')], default='user', max_length=20, verbose_name='Тип облікового запису')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('description', models.TextField(blank=True, verbose_name='Опис/Призначення')),
                ('status', models.CharField(choices=[('active', 'Активний'), ('disabled', 'Відключений'), ('expired', 'Прострочений'), ('locked', 'Заблокований')], default='active', max_length=20, verbose_name='Статус')),
                ('password_created', models.DateTimeField(auto_now_add=True, verbose_name='Пароль створено')),
                ('password_expires', models.DateTimeField(blank=True, null=True, verbose_name='Пароль діє до')),
                ('last_password_change', models.DateTimeField(blank=True, null=True, verbose_name='Остання зміна пароля')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Призначено користувачу')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Створено користувачем')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_accounts', to='inventory.system', verbose_name='Система')),
            ],
            options={
                'verbose_name': 'Обліковий запис системи',
                'verbose_name_plural': 'Облікові записи систем',
                'ordering': ['system__name', 'username'],
            },
        ),
        migrations.AddField(
            model_name='system',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.systemcategory', verbose_name='Категорія'),
        ),
        migrations.AddField(
            model_name='system',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_systems', to=settings.AUTH_USER_MODEL, verbose_name='Власник системи'),
        ),
        migrations.CreateModel(
            name='PasswordAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'Перегляд'), ('copy', 'Копіювання'), ('edit', 'Редагування'), ('create', 'Створення'), ('delete', 'Видалення'), ('generate', 'Генерація')], max_length=20, verbose_name='Дія')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адреса')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Час дії')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='inventory.systemaccount', verbose_name='Обліковий запис')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Лог доступу до паролів',
                'verbose_name_plural': 'Логи доступу до паролів',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalSystemAccount',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name="Ім'я користувача")),
                ('account_type', models.CharField(choices=[('admin', 'Адміністратор'), ('user', 'Користувач'), ('service', 'Сервісний'), ('readonly', 'Тільки читання'), ('api', 'API ключ'), ('other', 'Інше')], default='user', max_length=20, verbose_name='Тип облікового запису')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('description', models.TextField(blank=True, verbose_name='Опис/Призначення')),
                ('status', models.CharField(choices=[('active', 'Активний'), ('disabled', 'Відключений'), ('expired', 'Прострочений'), ('locked', 'Заблокований')], default='active', max_length=20, verbose_name='Статус')),
                ('password_created', models.DateTimeField(blank=True, editable=False, verbose_name='Пароль створено')),
                ('password_expires', models.DateTimeField(blank=True, null=True, verbose_name='Пароль діє до')),
                ('last_password_change', models.DateTimeField(blank=True, null=True, verbose_name='Остання зміна пароля')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Оновлено')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assigned_to', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Призначено користувачу')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Створено користувачем')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('system', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.system', verbose_name='Система')),
            ],
            options={
                'verbose_name': 'historical Обліковий запис системи',
                'verbose_name_plural': 'historical Облікові записи систем',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSystem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва системи')),
                ('system_type', models.CharField(choices=[('web', 'Веб-система'), ('database', 'База даних'), ('server', 'Сервер'), ('network', 'Мережеве обладнання'), ('cloud', 'Хмарний сервіс'), ('software', 'Програмне забезпечення'), ('service', 'Сервіс'), ('other', 'Інше')], default='web', max_length=20, verbose_name='Тип системи')),
                ('url', models.URLField(blank=True, verbose_name='URL/Адреса')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адреса')),
                ('port', models.PositiveIntegerField(blank=True, null=True, verbose_name='Порт')),
                ('description', models.TextField(blank=True, verbose_name='Опис системи')),
                ('criticality', models.CharField(choices=[('low', 'Низька'), ('medium', 'Середня'), ('high', 'Висока'), ('critical', 'Критична')], default='medium', max_length=10, verbose_name='Критичність')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Оновлено')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.systemcategory', verbose_name='Категорія')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Власник системи')),
            ],
            options={
                'verbose_name': 'historical Система',
                'verbose_name_plural': 'historical Системи',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='systemaccount',
            index=models.Index(fields=['system', 'status'], name='inventory_s_system__824694_idx'),
        ),
        migrations.AddIndex(
            model_name='systemaccount',
            index=models.Index(fields=['assigned_to', 'status'], name='inventory_s_assigne_e014d9_idx'),
        ),
        migrations.AddIndex(
            model_name='systemaccount',
            index=models.Index(fields=['account_type'], name='inventory_s_account_163ca3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='systemaccount',
            unique_together={('system', 'username')},
        ),
        migrations.AddIndex(
            model_name='system',
            index=models.Index(fields=['system_type', 'criticality'], name='inventory_s_system__4dae4a_idx'),
        ),
        migrations.AddIndex(
            model_name='system',
            index=models.Index(fields=['category', 'is_active'], name='inventory_s_categor_da69bd_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordaccesslog',
            index=models.Index(fields=['account', 'timestamp'], name='inventory_p_account_4f1118_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordaccesslog',
            index=models.Index(fields=['user', 'action'], name='inventory_p_user_id_9c29bc_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordaccesslog',
            index=models.Index(fields=['timestamp'], name='inventory_p_timesta_6afa46_idx'),
        ),
    ]
