# Generated by Django 5.2.11 on 2026-02-27 06:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0003_system_systemcategory_systemaccount_system_category_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="equipment",
            index=models.Index(
                fields=["warranty_until", "status"],
                name="inventory_e_warrant_14705f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="equipment",
            index=models.Index(
                fields=["purchase_date", "status"],
                name="inventory_e_purchas_6805dd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="equipment",
            index=models.Index(
                fields=["next_maintenance_date"], name="inventory_e_next_ma_2ff86a_idx"
            ),
        ),
    ]
