# Generated by Django 5.2.11 on 2026-02-27 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_add_equipment_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="system",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.systemcategory",
                verbose_name="Категорія",
            ),
        ),
        migrations.AlterField(
            model_name="system",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owned_systems",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Власник системи",
            ),
        ),
    ]
