# Generated by Django 5.2.11 on 2026-03-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_alter_system_category_alter_system_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="peripheraldevice",
            name="barcode_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="barcodes/", verbose_name="Штрих-код"
            ),
        ),
        migrations.AddField(
            model_name="peripheraldevice",
            name="inventory_number",
            field=models.CharField(
                blank=True,
                help_text="Внутрішній номер організації",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Інвентарний номер",
            ),
        ),
        migrations.AddField(
            model_name="peripheraldevice",
            name="qrcode_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="qrcodes/", verbose_name="QR-код"
            ),
        ),
    ]
