# Generated by Django 5.2.11 on 2026-03-02 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_peripheral_inventory_codes"),
        ("licenses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="software",
            name="license",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="licensed_software",
                to="licenses.license",
                verbose_name="Лицензія",
            ),
        ),
    ]
