# Generated by Django 5.2.11 on 2026-03-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_license_device_to_software"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="short_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Скорочена назва"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="name",
            field=models.CharField(
                max_length=200, verbose_name="Повна назва постачальника"
            ),
        ),
    ]
