# Generated by Django 5.2.11 on 2026-03-10 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_add_supplier_short_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Назва")),
                ("description", models.TextField(blank=True, verbose_name="Опис")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активне"),
                ),
            ],
            options={
                "verbose_name": "Місце зберігання",
                "verbose_name_plural": "Місця зберігання",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="sparepart",
            name="storage_location",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Місце зберігання (стара)"
            ),
        ),
        migrations.AddField(
            model_name="sparepart",
            name="storage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="spare_parts",
                to="inventory.storagelocation",
                verbose_name="Місце зберігання",
            ),
        ),
    ]
