# Generated by Django 5.2.11 on 2026-03-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_add_storage_location_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="bios_version",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Версія BIOS/UEFI"
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="disk_model",
            field=models.TextField(
                blank=True, verbose_name="Накопичувачі (деталізовано)"
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="display",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Екран / Монітор"
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="motherboard",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Материнська плата"
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="motherboard_serial",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="Серійний номер материнської плати",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="network_adapter",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Мережевий адаптер"
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="power_supply",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Блок живлення"
            ),
        ),
        migrations.AddField(
            model_name="historicalequipment",
            name="bios_version",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Версія BIOS/UEFI"
            ),
        ),
        migrations.AddField(
            model_name="historicalequipment",
            name="disk_model",
            field=models.TextField(
                blank=True, verbose_name="Накопичувачі (деталізовано)"
            ),
        ),
        migrations.AddField(
            model_name="historicalequipment",
            name="display",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Екран / Монітор"
            ),
        ),
        migrations.AddField(
            model_name="historicalequipment",
            name="motherboard",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Материнська плата"
            ),
        ),
        migrations.AddField(
            model_name="historicalequipment",
            name="motherboard_serial",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="Серійний номер материнської плати",
            ),
        ),
        migrations.AddField(
            model_name="historicalequipment",
            name="network_adapter",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Мережевий адаптер"
            ),
        ),
        migrations.AddField(
            model_name="historicalequipment",
            name="power_supply",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Блок живлення"
            ),
        ),
    ]
