# Generated by Django 5.2.11 on 2026-03-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_add_detailed_hardware_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsystem",
            name="system_type",
            field=models.CharField(
                choices=[
                    ("web", "Веб-система"),
                    ("database", "База даних"),
                    ("server", "Сервер"),
                    ("network", "Мережеве обладнання"),
                    ("cloud", "Хмарний сервіс"),
                    ("software", "Програмне забезпечення"),
                    ("service", "Сервіс"),
                    ("os", "Операційна система"),
                    ("email", "Електронна пошта"),
                    ("vpn", "VPN"),
                    ("firewall", "Файрвол"),
                    ("storage", "Сховище даних"),
                    ("monitoring", "Моніторинг"),
                    ("backup", "Резервне копіювання"),
                    ("other", "Інше"),
                ],
                default="web",
                max_length=20,
                verbose_name="Тип системи",
            ),
        ),
        migrations.AlterField(
            model_name="system",
            name="system_type",
            field=models.CharField(
                choices=[
                    ("web", "Веб-система"),
                    ("database", "База даних"),
                    ("server", "Сервер"),
                    ("network", "Мережеве обладнання"),
                    ("cloud", "Хмарний сервіс"),
                    ("software", "Програмне забезпечення"),
                    ("service", "Сервіс"),
                    ("os", "Операційна система"),
                    ("email", "Електронна пошта"),
                    ("vpn", "VPN"),
                    ("firewall", "Файрвол"),
                    ("storage", "Сховище даних"),
                    ("monitoring", "Моніторинг"),
                    ("backup", "Резервне копіювання"),
                    ("other", "Інше"),
                ],
                default="web",
                max_length=20,
                verbose_name="Тип системи",
            ),
        ),
    ]
