# Generated by Django 5.2.11 on 2026-03-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_add_system_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="delivery_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("nova_poshta", "Нова Пошта"),
                    ("ukrposhta", "Укрпошта"),
                    ("meest", "Meest"),
                    ("self_pickup", "Самовивіз"),
                    ("courier", "Кур'єр"),
                    ("other", "Інше"),
                ],
                default="",
                max_length=20,
                verbose_name="Спосіб доставки",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="tracking_number",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="ТТН / Трекінг номер",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="add_to_inventory",
            field=models.BooleanField(
                default=True, verbose_name="Додати до запасів при отриманні"
            ),
        ),
    ]
