# Generated by Django 5.2.11 on 2026-03-11 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0012_add_delivery_fields_to_purchase_order"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Назва")),
                (
                    "contract_number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Номер договору"
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("SERVICE", "Сервісне обслуговування"),
                            ("SUPPLY", "Постачання"),
                            ("LEASE", "Оренда"),
                            ("LICENSE", "Ліцензія"),
                            ("WARRANTY", "Гарантія"),
                            ("SUPPORT", "Підтримка"),
                            ("OTHER", "Інше"),
                        ],
                        default="SERVICE",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Чернетка"),
                            ("ACTIVE", "Активний"),
                            ("EXPIRED", "Закінчився"),
                            ("TERMINATED", "Розірваний"),
                            ("SUSPENDED", "Призупинений"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "counterparty",
                    models.CharField(max_length=255, verbose_name="Контрагент"),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("start_date", models.DateField(verbose_name="Дата початку")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата закінчення"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Сума",
                    ),
                ),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="contracts/"),
                ),
                ("auto_renew", models.BooleanField(default=False)),
                ("reminder_days", models.IntegerField(default=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "equipment",
                    models.ManyToManyField(
                        blank=True, related_name="contracts", to="inventory.equipment"
                    ),
                ),
                (
                    "responsible_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contracts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Договір",
                "verbose_name_plural": "Договори",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EquipmentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Назва шаблону"),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PC", "Стаціонарний ПК"),
                            ("WORK", "Робоча станція"),
                            ("SRV", "Сервер"),
                            ("PRN", "Принтер"),
                            ("LAPTOP", "Ноутбук"),
                            ("TABLET", "Планшет"),
                            ("PHONE", "Телефон"),
                            ("MONITOR", "Монітор"),
                            ("NETWORK", "Мережеве обладнання"),
                            ("OTH", "Інше"),
                        ],
                        default="PC",
                        max_length=20,
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "model_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("cpu", models.CharField(blank=True, default="", max_length=255)),
                ("ram", models.CharField(blank=True, default="", max_length=100)),
                ("storage", models.CharField(blank=True, default="", max_length=255)),
                ("gpu", models.CharField(blank=True, default="", max_length=255)),
                (
                    "operating_system",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "motherboard",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "network_adapter",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "power_supply",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "default_location",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("default_status", models.CharField(default="WORKING", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipment_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Шаблон обладнання",
                "verbose_name_plural": "Шаблони обладнання",
                "ordering": ["-created_at"],
            },
        ),
    ]
