# Generated by Django 5.2.11 on 2026-03-16 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0015_add_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="equipment",
            name="idx_equipment_purchase_date",
        ),
    ]
