# Generated by Django 5.2.11 on 2026-03-19 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0016_remove_equipment_idx_equipment_purchase_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Counterparty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Назва організації"),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Скорочена назва"
                    ),
                ),
                (
                    "edrpou",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Код ЄДРПОУ"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Адреса")),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Контактна особа"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=50, verbose_name="Телефон"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примітки")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активний"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Створено"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Оновлено"),
                ),
            ],
            options={
                "verbose_name": "Контрагент",
                "verbose_name_plural": "Контрагенти",
                "ordering": ["name"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="purchaseorderitem",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="item_name",
            field=models.CharField(
                blank=True,
                help_text="Для обладнання або іншого типу — назва вручну",
                max_length=300,
                verbose_name="Назва позиції",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("SPARE_PART", "Запчастина"),
                    ("EQUIPMENT", "Обладнання"),
                    ("OTHER", "Інше"),
                ],
                default="SPARE_PART",
                max_length=20,
                verbose_name="Тип позиції",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="spare_part",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.sparepart",
                verbose_name="Запчастина",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="counterparty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.counterparty",
                verbose_name="Контрагент (покупець)",
            ),
        ),
    ]
