# Generated by Django 5.2.11 on 2026-03-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0017_counterparty_alter_purchaseorderitem_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="sparepart",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("SPARE_PART", "Запчастина"),
                    ("EQUIPMENT", "Обладнання"),
                    ("CONSUMABLE", "Витратний матеріал"),
                    ("COMPONENT", "Комплектуючі"),
                    ("TOOL", "Інструмент"),
                    ("OTHER", "Інше"),
                ],
                default="SPARE_PART",
                max_length=20,
                verbose_name="Тип товару",
            ),
        ),
        migrations.AlterField(
            model_name="sparepart",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Назва"),
        ),
    ]
