# Generated by Django 5.2.11 on 2026-03-23 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0018_sparepart_item_type_alter_sparepart_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Прізвище"),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Ім'я")),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="По батькові"
                    ),
                ),
                (
                    "position",
                    models.CharField(blank=True, max_length=200, verbose_name="Посада"),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("IT", "IT відділ"),
                            ("HR", "Кадри"),
                            ("FIN", "Бухгалтерія"),
                            ("SALES", "Відділ продажів"),
                            ("MGMT", "Керівництво"),
                            ("PROD", "Виробництво"),
                            ("LOG", "Логістика"),
                            ("LEGAL", "Юридичний"),
                            ("OTHER", "Інше"),
                        ],
                        max_length=20,
                        verbose_name="Відділ",
                    ),
                ),
                (
                    "custom_department",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Відділ (інший)"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=50, verbose_name="Телефон"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активний"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примітки")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Співробітник",
                "verbose_name_plural": "Співробітники",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.AlterField(
            model_name="equipment",
            name="current_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_equipment",
                to="inventory.employee",
                verbose_name="Поточний користувач",
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="responsible_person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="responsible_equipment",
                to="inventory.employee",
                verbose_name="Відповідальна особа",
            ),
        ),
        migrations.AlterField(
            model_name="historicalequipment",
            name="current_user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="inventory.employee",
                verbose_name="Поточний користувач",
            ),
        ),
        migrations.AlterField(
            model_name="historicalequipment",
            name="responsible_person",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="inventory.employee",
                verbose_name="Відповідальна особа",
            ),
        ),
    ]
