# Generated by Django 5.2.11 on 2026-03-26 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0019_employee_alter_equipment_current_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenanceschedule",
            name="responsible_person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.employee",
                verbose_name="Відповідальна особа",
            ),
        ),
    ]
