# Generated by Django 5.2.11 on 2026-03-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0020_alter_maintenanceschedule_responsible_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="sparepart",
            name="manufacturer",
            field=models.CharField(blank=True, max_length=200, verbose_name="Виробник"),
        ),
    ]
