# Generated by Django 4.2.23 on 2025-08-07 10:20

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone
import inventory.validators
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, help_text='Формат: +380501234567', max_length=20, validators=[inventory.validators.validate_phone_number], verbose_name='Телефон')),
                ('mobile_phone', models.CharField(blank=True, max_length=20, validators=[inventory.validators.validate_phone_number], verbose_name='Мобільний телефон')),
                ('position', models.CharField(blank=True, choices=[('MANAGER', 'Менеджер'), ('DEVELOPER', 'Розробник'), ('ANALYST', 'Аналітик'), ('ADMIN', 'Адміністратор'), ('SPECIALIST', 'Спеціаліст'), ('DIRECTOR', 'Директор'), ('COORDINATOR', 'Координатор'), ('ASSISTANT', 'Асистент'), ('OTHER', 'Інша')], max_length=20, verbose_name='Посада')),
                ('custom_position', models.CharField(blank=True, help_text='Якщо вашої посади немає в списку', max_length=100, verbose_name='Посада (інша)')),
                ('department', models.CharField(blank=True, choices=[('IT', 'IT відділ'), ('HR', 'Відділ кадрів'), ('FINANCE', 'Фінансовий відділ'), ('MARKETING', 'Маркетинг'), ('SALES', 'Продажі'), ('MANAGEMENT', 'Управління'), ('OPERATIONS', 'Операційний відділ'), ('SUPPORT', 'Служба підтримки'), ('OTHER', 'Інший')], max_length=20, verbose_name='Відділ')),
                ('custom_department', models.CharField(blank=True, help_text='Якщо вашого відділу немає в списку', max_length=100, verbose_name='Відділ (інший)')),
                ('office_location', models.CharField(blank=True, max_length=100, verbose_name='Місцезнаходження офісу')),
                ('room_number', models.CharField(blank=True, max_length=20, verbose_name='Номер кімнати')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Дата прийняття на роботу')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата народження')),
                ('notification_preferences', models.JSONField(blank=True, default=dict, help_text="JSON об'єкт з налаштуваннями уведомлень", verbose_name='Налаштування уведомлень')),
                ('timezone', models.CharField(default='Europe/Kiev', max_length=50, verbose_name='Часовий пояс')),
                ('language', models.CharField(choices=[('uk', 'Українська'), ('en', 'English'), ('ru', 'Русский')], default='uk', max_length=10, verbose_name='Мова інтерфейсу')),
                ('is_temporary', models.BooleanField(default=False, verbose_name='Тимчасовий співробітник')),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Повний робочий день'), ('PART_TIME', 'Неповний робочий день'), ('CONTRACT', 'Контракт'), ('INTERN', 'Стажер')], default='FULL_TIME', max_length=20, verbose_name='Тип зайнятості')),
                ('bio', models.TextField(blank=True, help_text='Коротка інформація про співробітника', verbose_name='Біографія')),
                ('skills', models.TextField(blank=True, help_text='Професійні навички через кому', verbose_name='Навички')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, verbose_name="Контактна особа (ім'я)")),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, validators=[inventory.validators.validate_phone_number], verbose_name='Контактна особа (телефон)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Користувач',
                'verbose_name_plural': 'Користувачі',
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCustomUser',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_index=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, help_text='Формат: +380501234567', max_length=20, validators=[inventory.validators.validate_phone_number], verbose_name='Телефон')),
                ('mobile_phone', models.CharField(blank=True, max_length=20, validators=[inventory.validators.validate_phone_number], verbose_name='Мобільний телефон')),
                ('position', models.CharField(blank=True, choices=[('MANAGER', 'Менеджер'), ('DEVELOPER', 'Розробник'), ('ANALYST', 'Аналітик'), ('ADMIN', 'Адміністратор'), ('SPECIALIST', 'Спеціаліст'), ('DIRECTOR', 'Директор'), ('COORDINATOR', 'Координатор'), ('ASSISTANT', 'Асистент'), ('OTHER', 'Інша')], max_length=20, verbose_name='Посада')),
                ('custom_position', models.CharField(blank=True, help_text='Якщо вашої посади немає в списку', max_length=100, verbose_name='Посада (інша)')),
                ('department', models.CharField(blank=True, choices=[('IT', 'IT відділ'), ('HR', 'Відділ кадрів'), ('FINANCE', 'Фінансовий відділ'), ('MARKETING', 'Маркетинг'), ('SALES', 'Продажі'), ('MANAGEMENT', 'Управління'), ('OPERATIONS', 'Операційний відділ'), ('SUPPORT', 'Служба підтримки'), ('OTHER', 'Інший')], max_length=20, verbose_name='Відділ')),
                ('custom_department', models.CharField(blank=True, help_text='Якщо вашого відділу немає в списку', max_length=100, verbose_name='Відділ (інший)')),
                ('office_location', models.CharField(blank=True, max_length=100, verbose_name='Місцезнаходження офісу')),
                ('room_number', models.CharField(blank=True, max_length=20, verbose_name='Номер кімнати')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Дата прийняття на роботу')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата народження')),
                ('notification_preferences', models.JSONField(blank=True, default=dict, help_text="JSON об'єкт з налаштуваннями уведомлень", verbose_name='Налаштування уведомлень')),
                ('timezone', models.CharField(default='Europe/Kiev', max_length=50, verbose_name='Часовий пояс')),
                ('language', models.CharField(choices=[('uk', 'Українська'), ('en', 'English'), ('ru', 'Русский')], default='uk', max_length=10, verbose_name='Мова інтерфейсу')),
                ('is_temporary', models.BooleanField(default=False, verbose_name='Тимчасовий співробітник')),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Повний робочий день'), ('PART_TIME', 'Неповний робочий день'), ('CONTRACT', 'Контракт'), ('INTERN', 'Стажер')], default='FULL_TIME', max_length=20, verbose_name='Тип зайнятості')),
                ('bio', models.TextField(blank=True, help_text='Коротка інформація про співробітника', verbose_name='Біографія')),
                ('skills', models.TextField(blank=True, help_text='Професійні навички через кому', verbose_name='Навички')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, verbose_name="Контактна особа (ім'я)")),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, validators=[inventory.validators.validate_phone_number], verbose_name='Контактна особа (телефон)')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Оновлено')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Користувач',
                'verbose_name_plural': 'historical Користувачі',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_layout', models.JSONField(blank=True, default=dict, verbose_name='Налаштування дашборду')),
                ('quick_actions', models.JSONField(blank=True, default=list, help_text='Список швидких дій для користувача', verbose_name='Швидкі дії')),
                ('items_per_page', models.IntegerField(choices=[(10, '10'), (25, '25'), (50, '50'), (100, '100')], default=25, verbose_name='Елементів на сторінці')),
                ('default_equipment_view', models.CharField(choices=[('list', 'Список'), ('cards', 'Картки'), ('table', 'Таблиця')], default='table', max_length=20, verbose_name='Вигляд обладнання за замовчуванням')),
                ('email_digest_frequency', models.CharField(choices=[('never', 'Ніколи'), ('daily', 'Щодня'), ('weekly', 'Щотижня'), ('monthly', 'Щомісяця')], default='weekly', max_length=20, verbose_name='Частота email дайджесту')),
            ],
            options={
                'verbose_name': 'Профіль користувача',
                'verbose_name_plural': 'Профілі користувачів',
            },
        ),
    ]
