# Generated by Django 5.2.11 on 2026-03-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/", verbose_name="Аватарка"
            ),
        ),
        migrations.AddField(
            model_name="historicalcustomuser",
            name="avatar",
            field=models.TextField(
                blank=True, max_length=100, null=True, verbose_name="Аватарка"
            ),
        ),
    ]
