# Generated by Django 5.2.11 on 2026-03-02 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_license_device_to_software"),
        ("licenses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicallicense",
            name="device",
        ),
        migrations.RemoveField(
            model_name="license",
            name="device",
        ),
        migrations.AddField(
            model_name="historicallicense",
            name="software",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="inventory.software",
                verbose_name="Програма",
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="software",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="licenses",
                to="inventory.software",
                verbose_name="Програма",
            ),
        ),
    ]
