# Generated by Django 5.2.11 on 2026-03-10 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_add_detailed_hardware_fields"),
        ("licenses", "0002_license_device_to_software"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicallicense",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Ліцензія",
                "verbose_name_plural": "historical Ліцензії",
            },
        ),
        migrations.AlterModelOptions(
            name="license",
            options={"verbose_name": "Ліцензія", "verbose_name_plural": "Ліцензії"},
        ),
        migrations.AddField(
            model_name="historicallicense",
            name="cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Вартість (грн)",
            ),
        ),
        migrations.AddField(
            model_name="historicallicense",
            name="is_perpetual",
            field=models.BooleanField(default=False, verbose_name="Безстрокова"),
        ),
        migrations.AddField(
            model_name="historicallicense",
            name="oem_device",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="inventory.equipment",
                verbose_name="Прив'язаний пристрій (OEM)",
            ),
        ),
        migrations.AddField(
            model_name="historicallicense",
            name="open_source_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GPL", "GPL"),
                    ("MIT", "MIT"),
                    ("APACHE", "Apache 2.0"),
                    ("BSD", "BSD"),
                    ("LGPL", "LGPL"),
                    ("MPL", "MPL"),
                    ("AGPL", "AGPL"),
                    ("OTHER", "Інша"),
                ],
                max_length=50,
                verbose_name="Тип Open Source ліцензії",
            ),
        ),
        migrations.AddField(
            model_name="historicallicense",
            name="trial_days",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Пробний період (днів)"
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Вартість (грн)",
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="is_perpetual",
            field=models.BooleanField(default=False, verbose_name="Безстрокова"),
        ),
        migrations.AddField(
            model_name="license",
            name="oem_device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="oem_licenses",
                to="inventory.equipment",
                verbose_name="Прив'язаний пристрій (OEM)",
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="open_source_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GPL", "GPL"),
                    ("MIT", "MIT"),
                    ("APACHE", "Apache 2.0"),
                    ("BSD", "BSD"),
                    ("LGPL", "LGPL"),
                    ("MPL", "MPL"),
                    ("AGPL", "AGPL"),
                    ("OTHER", "Інша"),
                ],
                max_length=50,
                verbose_name="Тип Open Source ліцензії",
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="trial_days",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Пробний період (днів)"
            ),
        ),
        migrations.AlterField(
            model_name="historicallicense",
            name="activations",
            field=models.IntegerField(default=1, verbose_name="Кількість активацій"),
        ),
        migrations.AlterField(
            model_name="historicallicense",
            name="description",
            field=models.TextField(blank=True, verbose_name="Опис"),
        ),
        migrations.AlterField(
            model_name="historicallicense",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="Кінець дії"),
        ),
        migrations.AlterField(
            model_name="historicallicense",
            name="key",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Ліцензійний ключ"
            ),
        ),
        migrations.AlterField(
            model_name="historicallicense",
            name="license_type",
            field=models.CharField(
                choices=[
                    ("COMMERCIAL", "Комерційна"),
                    ("FREEWARE", "Freeware"),
                    ("SHAREWARE", "Shareware"),
                    ("OPEN_SOURCE", "Open Source"),
                    ("TRIAL", "Trial (пробна)"),
                    ("OEM", "OEM"),
                    ("VOLUME", "Volume License (корпоративна)"),
                ],
                max_length=100,
                verbose_name="Тип ліцензії",
            ),
        ),
        migrations.AlterField(
            model_name="historicallicense",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Початок дії"),
        ),
        migrations.AlterField(
            model_name="historicallicense",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Користувач",
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="activations",
            field=models.IntegerField(default=1, verbose_name="Кількість активацій"),
        ),
        migrations.AlterField(
            model_name="license",
            name="description",
            field=models.TextField(blank=True, verbose_name="Опис"),
        ),
        migrations.AlterField(
            model_name="license",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="Кінець дії"),
        ),
        migrations.AlterField(
            model_name="license",
            name="key",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Ліцензійний ключ"
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="license_type",
            field=models.CharField(
                choices=[
                    ("COMMERCIAL", "Комерційна"),
                    ("FREEWARE", "Freeware"),
                    ("SHAREWARE", "Shareware"),
                    ("OPEN_SOURCE", "Open Source"),
                    ("TRIAL", "Trial (пробна)"),
                    ("OEM", "OEM"),
                    ("VOLUME", "Volume License (корпоративна)"),
                ],
                max_length=100,
                verbose_name="Тип ліцензії",
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Початок дії"),
        ),
        migrations.AlterField(
            model_name="license",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Користувач",
            ),
        ),
    ]
