# Generated by Django 5.2.11 on 2026-03-10 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0003_revamp_license_types"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicallicense",
            name="software",
        ),
        migrations.RemoveField(
            model_name="license",
            name="software",
        ),
    ]
