# Generated by Django 5.2.11 on 2026-03-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0004_remove_software_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallicense",
            name="manual_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Автоматично"),
                    ("SUSPENDED", "Призупинена"),
                    ("REVOKED", "Анульована"),
                ],
                default="",
                max_length=20,
                verbose_name="Ручний статус",
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="manual_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Автоматично"),
                    ("SUSPENDED", "Призупинена"),
                    ("REVOKED", "Анульована"),
                ],
                default="",
                max_length=20,
                verbose_name="Ручний статус",
            ),
        ),
        migrations.AlterField(
            model_name="historicallicense",
            name="license_type",
            field=models.CharField(
                choices=[
                    ("COMMERCIAL", "Комерційна"),
                    ("FREEWARE", "Freeware"),
                    ("EULA", "EULA (безкоштовне пропрієтарне)"),
                    ("SHAREWARE", "Shareware"),
                    ("OPEN_SOURCE", "Open Source"),
                    ("TRIAL", "Trial (пробна)"),
                    ("OEM", "OEM"),
                    ("VOLUME", "Volume License (корпоративна)"),
                    ("SUBSCRIPTION", "Підписка (SaaS)"),
                    ("SITE", "Site License"),
                    ("EDUCATIONAL", "Навчальна / Академічна"),
                    ("GOVERNMENT", "Державна"),
                ],
                max_length=100,
                verbose_name="Тип ліцензії",
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="license_type",
            field=models.CharField(
                choices=[
                    ("COMMERCIAL", "Комерційна"),
                    ("FREEWARE", "Freeware"),
                    ("EULA", "EULA (безкоштовне пропрієтарне)"),
                    ("SHAREWARE", "Shareware"),
                    ("OPEN_SOURCE", "Open Source"),
                    ("TRIAL", "Trial (пробна)"),
                    ("OEM", "OEM"),
                    ("VOLUME", "Volume License (корпоративна)"),
                    ("SUBSCRIPTION", "Підписка (SaaS)"),
                    ("SITE", "Site License"),
                    ("EDUCATIONAL", "Навчальна / Академічна"),
                    ("GOVERNMENT", "Державна"),
                ],
                max_length=100,
                verbose_name="Тип ліцензії",
            ),
        ),
    ]
